---
title: "Battle plan for JD+ related Tools"
format: pdf
format: html 
---

Beware to have 
- a state of affairs / state of the art overview
- goals set in perimeters (according to events)

## Now page

Currently working on (details in TOPICS..)

### JD+ online Documentation 

- GUI chap on SA and modelling features (Tanguy)
- Documenting new features and Holes (Anna)


### R packages 

- create a readme for rjdemetra page (Anna)
- readme and examples for each package (Both of us)
- generate github pages for all packages (together): reste : 

### GUI tests

- HF in GUI: start before Bxls (Anna)


## This file 

### Objectives 

- define products and steps unambiguously

- highlight was has to be done for up coming presentations (Stace, Tsaug meetings...)

### Scope 

All JD+ related tools : GUI and R packages 

R packages 

- dvlpt 
- test 
- doc (functions, readme)

GUI 

- test new features (HF,...)
- improve online documentation 

(no mass testing on basic functions, a priori no )

## Next Events 

What do we expect ? what do we bring ?

### Q&A NBB 23 nov

- be ready on all remaining ABS questions 

### BXLS 4,5 dec 

### TSACE 13 dec 

#### R team update 

- dvlpts ?:  
- tests
- doc 
- communication (Webinar, newlsetters, blog, ...)
    
#### JD+ online doc update

### TSAUG 13 dec 

- Presentation on WS wrangling (Tanguy)

- HF with GUI latest test (Anna)

### Webinar in February 


## TOPICS to work on 

### JD+ online doc 

### R packages V3

#### MAP of the R ecosystem

cf slides June, do smth better 

#### Tests and doc (old features)

#### New features (test and doc)

(Anna)
-	Pré-identification des gros outliers avant la sélection log/level (impact limité)
(rjdx13 and tramo seats...)

-	Intégration du pré-ajustement LP dans Tramo (comparable au X13) ? Not clear...(in GUI as well)

-	Sélection automatique des variables de jours ouvrables (amélioration dans Tramo et nouveauté dans X13, solution identique dans les deux algorithmes)

(tramo and or x13 ?)

- Refresh in R 

all ok 
left:
- current policy (AO)
- time span definition 


#### Habillage (Appearance)

- pay attention to title, readme

- github pages

- bring v3 pages to RJDemetra level !!!

- doc functions, examples 

- vignettes by topic

#### Orga repos and naming issues 

- orga github: regrouper tout le R v2 et v3

- ajouter au readme
installation depuis github: quelle branche 
- github remotes installe depuis la develop 
- la release (= le zip vu que pas de cran)

#### Prints

- change "airline" display when printing a spec 

#### rjd3x13

noms (alain ?)
spec_x13-> x13_spec
idem pour fast 
idem dans tramo 
    --> fait par Alain !
    
(id in tramoseats)

bias correction : non existing ?

#### rjd3tramoseats 

(look into Java: Tanguy)
- bias correction ?


#### rjdemetra3 

everything up to date ? 
readme
doc 
 
#### JD Cruncher in V3

- does it work with cruncher v3 ? (same demetra_m)

- qd champagnes ipi ica: test prod in GUI v3 and fully in R (exp for DT²)

#### rjdqa en V3 ?


#### rjd3toolkit 

- trigonometric regressors

- sarima estimation

- UC arima decomposition (see Ine) (lack of info)

#### rjd3highfreq 

#### rjd3stl 

see what is M stl

#### rjd3bench

#### rjd3sts 

#### rjd3revisions


### R packages V2


#### rjdqa 

- resuscitate ? reparametrer ?
alain : tableau supplementaitre

#### JD Cruncher 

- parametrage poids indicateurs: up date doc + example! done ??

- ajouter valeurs coefficients et p-values (pour selection cjo) 
aujourd'hui: ajout params dans options d'output, lecture ad hoc de demetra_m.csv
but lire direct avec JDCruncher (to do 1h)

- test validité chemin avant de cruncher (to do 1h)

#### rjdworkspace 

everything up to date ?





