---
title: "T-rjd3x13 Training test vs GUI"
format: html
---

```{r}
#| label: loading-rjdverse
#| echo: true
#| eval: true
library("rjd3toolkit")
library("rjd3x13")
```

### TO do 

- replicate this for tramo seats (customized exo book + tests)


### Forecasted calendar effects

same series RF3030 and regressors GUI 3.7.1 and here 

```{r}

## Import des données ----------------------------------------------------------

# Données CSV
# ipi <- read.csv2(file.path("Data", "IPI_nace4.csv"))

ipi <- read.csv2("C:/Users/YWYD5I/Documents/Formation-INS-Cameroun-Juin2026/Donnees/IPI_nace4.csv")
# obj comp avec GUI 

ipi$DATE <- as.Date(ipi$DATE, format = "%d/%m/%Y")
ipi[, -1] <- sapply(ipi[, -1], as.numeric)
View(ipi)

# # Donnees excel
# ipi_nace4_ind <- read.xlsx(
#     file.path("V:", "Formations-Stats", "CVS-CJO", "Donnees", "IPI_nace4_ind.xlsx"),
#     detectDates = TRUE, sheet = 1L
# )
# ipi_nace4_ind$date <- as.Date(ipi_nace4_ind$date)
# # View(ipi_nace4_ind)

# Visualisation de la série
ipi[1, "RF3030"]


## Manipulation des données ----------------------------------------------------

# Création d'un objet ts en R
y_raw <- ts(
    ipi[, "RF3030"],
    frequency = 12,
    start = c(1990, 1))
y_raw[1]

# Creating calendar regressors from a calendar

# Step 1: Create national (or other see doc) calendar if needed

# French calendar
french_calendar <- national_calendar(
    days = list(
        fixed_day(7, 14), # Bastille Day
        fixed_day(5, 8, validity = list(start = "1982-05-08")), # End of 2nd WW
        special_day("NEWYEAR"),
        special_day("CHRISTMAS"),
        special_day("MAYDAY"),
        special_day("EASTERMONDAY"),
        special_day("ASCENSION"),
        special_day("WHITMONDAY"),
        special_day("ASSUMPTION"),
        special_day("ALLSAINTSDAY"),
        special_day("ARMISTICE")
    )
)


### Step 2: Create regressors

# Create set of (6) regressors every day is different, contrast with Sunday,
# based on french national calendar
regs_td <- rjd3toolkit::calendar_td(
    calendar = french_calendar,
    # formats the regressor like your raw series (length, frequency..)
   # s = y_raw, # attention va empecher la prevision
    frequency = 12, start=start(y_raw), length = length(y_raw)+3*12,
    groups = c(1, 2, 3, 4, 5, 6, 0),
    contrasts = TRUE
)
View(regs_td)

# create an intervention variable (to be allocated to "trend")
iv1 <- intervention_variable(
    s = y_raw,
    starts = "2015-01-01",
    ends = "2015-12-01"
)


# regressors can be any TS object

#  Step 3: Create a modelling context

# Gather regressors into a list
my_regressors <- list(
    Monday = regs_td[, 1],
    Tuesday = regs_td[, 2],
    Wednesday = regs_td[, 3],
    Thursday = regs_td[, 4],
    Friday = regs_td[, 5],
    Saturday = regs_td[, 6],
    reg1 = iv1
)

# create modelling context
my_context <- modelling_context(variables = my_regressors)
# check variables present in modelling context
rjd3toolkit::.r2jd_modellingcontext(my_context)$getTsVariableDictionary()


### Step 4: Add regressors to specification

x13_spec <- rjd3x13::x13_spec("rsa3")
x13_spec_user_defined <- rjd3toolkit::set_tradingdays(
    x = x13_spec,
    option = "UserDefined",
    uservariable = c(
        "r.Monday",
        "r.Tuesday",
        "r.Wednesday",
        "r.Thursday",
        "r.Friday",
        "r.Saturday"
    ),
    test = "None"
)

x13_spec_user_defined

# step 5: define user defined output 
ud<-rjd3x13::x13_dictionary()

# add intervention variable to spec, choosing the component to allocate
# the effects to TREND
x13_spec_user_defined <- add_usrdefvar(
    x = x13_spec_user_defined,
    group = "r",
    name = "reg1",
    label = "iv1",
    regeffect = "Trend"
)

x13_spec_user_defined$regarima$regression$users


# step 5b: add a TC which will spill onto forecast 

# Step 6: Estimate with context and user-defined output 

sa_x13_ud <- rjd3x13::x13(y_raw, x13_spec_user_defined, context = my_context, userdefined = ud)

summary(sa_x13_ud)

```


#### calendar effects

```{r}
sa_x13_ud$user_defined$y
sa_x13_ud$user_defined$y_f
sa_x13_ud$user_defined$det
sa_x13_ud$user_defined$det_f
sa_x13_ud$user_defined$cal
sa_x13_ud$user_defined$cal_f # pb car à 1 check GUI 
sa_x13_ud$user_defined$cal_b
sa_x13_ud$user_defined$ycal
sa_x13_ud$user_defined$ycal_f
sa_x13_ud$user_defined$ycal_b
sa_x13_ud$user_defined$tde
sa_x13_ud$user_defined$tde_f
sa_x13_ud$user_defined$sa
sa_x13_ud$user_defined$t

sa_x13_ud$user_defined$i
sa_x13_ud$user_defined$sa_f
sa_x13_ud$user_defined$t_f

sa_x13_ud$user_defined$s
sa_x13_ud$user_defined$s_f



sa_x13_ud$user_defined$i_f
sa_x13_ud$user_defined$out_t
sa_x13_ud$user_defined$out_s
sa_x13_ud$user_defined$out_i
sa_x13_ud$user_defined$reg_t
sa_x13_ud$user_defined$reg_s
sa_x13_ud$user_defined$reg_i
sa_x13_ud$user_defined$reg_sa
sa_x13_ud$user_defined$reg_u
sa_x13_ud$user_defined$reg_y
sa_x13_ud$user_defined$det_t
sa_x13_ud$user_defined$det_s
sa_x13_ud$user_defined$det_i
sa_x13_ud$user_defined$out_t_f
sa_x13_ud$user_defined$out_s_f
sa_x13_ud$user_defined$out_i_f

## check allocation 
sa_x13_ud$user_defined$reg_t_f
sa_x13_ud$user_defined$reg_s_f
sa_x13_ud$user_defined$reg_i_f
sa_x13_ud$user_defined$reg_sa_f
sa_x13_ud$user_defined$reg_u_f
sa_x13_ud$user_defined$reg_y_f
sa_x13_ud$user_defined$det_t_f
sa_x13_ud$user_defined$det_s_f
sa_x13_ud$user_defined$det_i_f
sa_x13_ud$user_defined$out_t_b
sa_x13_ud$user_defined$out_s_b
sa_x13_ud$user_defined$out_i_b
sa_x13_ud$user_defined$reg_t_b
sa_x13_ud$user_defined$reg_s_b
sa_x13_ud$user_defined$reg_i_b
sa_x13_ud$user_defined$reg_sa_b
sa_x13_ud$user_defined$reg_u_b
sa_x13_ud$user_defined$reg_y_b
sa_x13_ud$user_defined$det_t_b
sa_x13_ud$user_defined$det_s_b
sa_x13_ud$user_defined$det_i_b
## redef cf TEST 
sa_x13_ud$user_defined$decomposition.y_cmp
sa_x13_ud$user_defined$decomposition.y_cmp_f
sa_x13_ud$user_defined$decomposition.y_cmp_b
sa_x13_ud$user_defined$decomposition.sa_cmp
sa_x13_ud$user_defined$decomposition.t_cmp
sa_x13_ud$user_defined$decomposition.s_cmp
sa_x13_ud$user_defined$decomposition.i_cmp
## end test
sa_x13_ud$user_defined$preadjustment.a1
sa_x13_ud$user_defined$preadjustment.a1a
sa_x13_ud$user_defined$preadjustment.a1b # backcast ? 
sa_x13_ud$user_defined$preadjustment.a6
sa_x13_ud$user_defined$preadjustment.a7
sa_x13_ud$user_defined$preadjustment.a8
### reallocations stored for final componenet computations ?
sa_x13_ud$user_defined$preadjustment.a8t
sa_x13_ud$user_defined$preadjustment.a8i
sa_x13_ud$user_defined$preadjustment.a8s
sa_x13_ud$user_defined$preadjustment.a9
sa_x13_ud$user_defined$preadjustment.a9
sa_x13_ud$user_defined$preadjustment.a9cal
sa_x13_ud$user_defined$preadjustment.a9u
sa_x13_ud$user_defined$preadjustment.a9sa
sa_x13_ud$user_defined$preadjustment.a9ser
sa_x13_ud$user_defined$decomposition.b1
sa_x13_ud$user_defined$decomposition.b2
sa_x13_ud$user_defined$decomposition.b3
sa_x13_ud$user_defined$decomposition.b4
sa_x13_ud$user_defined$decomposition.b5
sa_x13_ud$user_defined$decomposition.b6
sa_x13_ud$user_defined$decomposition.b7
sa_x13_ud$user_defined$decomposition.b8
sa_x13_ud$user_defined$decomposition.b9
sa_x13_ud$user_defined$decomposition.b10
sa_x13_ud$user_defined$decomposition.b11
sa_x13_ud$user_defined$decomposition.b13
sa_x13_ud$user_defined$decomposition.b17
sa_x13_ud$user_defined$decomposition.b20
sa_x13_ud$user_defined$decomposition.c1
sa_x13_ud$user_defined$decomposition.c2
sa_x13_ud$user_defined$decomposition.c4
sa_x13_ud$user_defined$decomposition.c5
sa_x13_ud$user_defined$decomposition.c6
sa_x13_ud$user_defined$decomposition.c7
sa_x13_ud$user_defined$decomposition.c9
sa_x13_ud$user_defined$decomposition.c10
sa_x13_ud$user_defined$decomposition.c11
sa_x13_ud$user_defined$decomposition.c13
sa_x13_ud$user_defined$decomposition.c17
sa_x13_ud$user_defined$decomposition.c20
sa_x13_ud$user_defined$decomposition.d1
sa_x13_ud$user_defined$decomposition.d2
sa_x13_ud$user_defined$decomposition.d4
sa_x13_ud$user_defined$decomposition.d5
sa_x13_ud$user_defined$decomposition.d6
sa_x13_ud$user_defined$decomposition.d7
sa_x13_ud$user_defined$decomposition.d8
sa_x13_ud$user_defined$decomposition.d9
sa_x13_ud$user_defined$decomposition.d10
sa_x13_ud$user_defined$decomposition.d11
sa_x13_ud$user_defined$decomposition.d12
sa_x13_ud$user_defined$decomposition.d13
sa_x13_ud$user_defined$decomposition.x11-all # pb !!
sa_x13_ud$user_defined$decomposition.icratio
sa_x13_ud$user_defined$decomposition.trend-filter # pb 
sa_x13_ud$user_defined$decomposition.seasonal-filters  # pb 
sa_x13_ud$user_defined$decomposition.d9-global-msr  # pb 
sa_x13_ud$user_defined$decomposition.d9-msr  # pb 
sa_x13_ud$user_defined$decomposition.d9-msr-table  # pb 
sa_x13_ud$user_defined$finals.d11
sa_x13_ud$user_defined$finals.d12
sa_x13_ud$user_defined$finals.d13
sa_x13_ud$user_defined$finals.d16
sa_x13_ud$user_defined$finals.d18
sa_x13_ud$user_defined$finals.d11a
sa_x13_ud$user_defined$finals.d12a
sa_x13_ud$user_defined$finals.d16a
sa_x13_ud$user_defined$finals.d18a
sa_x13_ud$user_defined$finals.d11b
sa_x13_ud$user_defined$finals.d12b
sa_x13_ud$user_defined$finals.d16b
sa_x13_ud$user_defined$finals.d18b
sa_x13_ud$user_defined$finals.e1
sa_x13_ud$user_defined$finals.e2
sa_x13_ud$user_defined$finals.e3
sa_x13_ud$user_defined$finals.e11
# pb not generated: mauvais ecriture, missing param : missing `` (TRAP°)
sa_x13_ud$user_defined$`diagnostics.seas-lin-combined`
sa_x13_ud$user_defined$`diagnostics.seas-lin-evolutive`
sa_x13_ud$user_defined$`diagnostics.seas-lin-stable` 
sa_x13_ud$user_defined$`diagnostics.seas-si-combined`
sa_x13_ud$user_defined$`diagnostics.seas-si-combined3`
sa_x13_ud$user_defined$`diagnostics.seas-si-evolutive`
sa_x13_ud$user_defined$`diagnostics.seas-si-stable`
sa_x13_ud$user_defined$`diagnostics.seas-res-combined`
sa_x13_ud$user_defined$`diagnostics.seas-res-combined3`
sa_x13_ud$user_defined$`diagnostics.seas-res-evolutive`
sa_x13_ud$user_defined$`diagnostics.seas-res-stable`
sa_x13_ud$user_defined$`diagnostics.seas-sa-combined`
sa_x13_ud$user_defined$`diagnostics.seas-sa-combined3`
sa_x13_ud$user_defined$`diagnostics.seas-sa-evolutive`
sa_x13_ud$user_defined$`diagnostics.seas-sa-stable`
sa_x13_ud$user_defined$`diagnostics.seas-i-combined`
sa_x13_ud$user_defined$`diagnostics.seas-i-combined3`
sa_x13_ud$user_defined$`diagnostics.seas-i-evolutive`
sa_x13_ud$user_defined$`diagnostics.seas-i-stable`
sa_x13_ud$user_defined$`diagnostics.seas-lin-qs`
sa_x13_ud$user_defined$`diagnostics.seas-lin-f`
sa_x13_ud$user_defined$`diagnostics.seas-lin-friedman`
sa_x13_ud$user_defined$`diagnostics.seas-lin-kw`
sa_x13_ud$user_defined$`diagnostics.seas-lin-periodogram`
sa_x13_ud$user_defined$`diagnostics.seas-lin-spectralpeaks`
sa_x13_ud$user_defined$`diagnostics.seas-res-qs`
sa_x13_ud$user_defined$`diagnostics.seas-res-f`
sa_x13_ud$user_defined$`diagnostics.seas-res-friedman`
sa_x13_ud$user_defined$`diagnostics.seas-res-kw`
sa_x13_ud$user_defined$`diagnostics.seas-res-periodogram`
sa_x13_ud$user_defined$`diagnostics.seas-res-spectralpeaks`
sa_x13_ud$user_defined$`diagnostics.seas-sa-qs`
sa_x13_ud$user_defined$`diagnostics.seas-sa-f`
sa_x13_ud$user_defined$`diagnostics.seas-sa-friedman`
sa_x13_ud$user_defined$`diagnostics.seas-sa-kw`
sa_x13_ud$user_defined$`diagnostics.seas-sa-periodogram`
sa_x13_ud$user_defined$`diagnostics.seas-sa-spectralpeaks`
sa_x13_ud$user_defined$`diagnostics.seas-i-qs`
sa_x13_ud$user_defined$`diagnostics.seas-i-f`
sa_x13_ud$user_defined$`diagnostics.seas-i-friedman`
sa_x13_ud$user_defined$`diagnostics.seas-i-kw`
sa_x13_ud$user_defined$`diagnostics.seas-i-periodogram`
sa_x13_ud$user_defined$`diagnostics.seas-i-spectralpeaks`
sa_x13_ud$user_defined$`diagnostics.seas-sa-ac1`
sa_x13_ud$user_defined$`diagnostics.td-res-all`
sa_x13_ud$user_defined$`diagnostics.td-res-last`
sa_x13_ud$user_defined$`diagnostics.td-sa-all`
sa_x13_ud$user_defined$`diagnostics.td-sa-last`
sa_x13_ud$user_defined$`diagnostics.td-i-all`
sa_x13_ud$user_defined$`diagnostics.td-i-last`
sa_x13_ud$user_defined$`diagnostics.fcast-insample-mean`
sa_x13_ud$user_defined$`diagnostics.fcast-outsample-mean`
sa_x13_ud$user_defined$`diagnostics.fcast-outsample-variance`
sa_x13_ud$user_defined$`m-statistics.m1`
sa_x13_ud$user_defined$`m-statistics.m2`
sa_x13_ud$user_defined$`m-statistics.m3`
sa_x13_ud$user_defined$`m-statistics.m4`
sa_x13_ud$user_defined$`m-statistics.m5`
sa_x13_ud$user_defined$`m-statistics.m6`
sa_x13_ud$user_defined$`m-statistics.m7`
sa_x13_ud$user_defined$`m-statistics.m8`
sa_x13_ud$user_defined$`m-statistics.m9`
sa_x13_ud$user_defined$`m-statistics.m10`
sa_x13_ud$user_defined$`m-statistics.m11`
sa_x13_ud$user_defined$`m-statistics.q`
sa_x13_ud$user_defined$`m-statistics.q-m2` 
## end of generation pb 
sa_x13_ud$user_defined$variancedecomposition.cycle
sa_x13_ud$user_defined$variancedecomposition.seasonality
sa_x13_ud$user_defined$variancedecomposition.irregular
sa_x13_ud$user_defined$variancedecomposition.tdh
sa_x13_ud$user_defined$variancedecomposition.others
sa_x13_ud$user_defined$variancedecomposition.total
sa_x13_ud$user_defined$quality.summary
sa_x13_ud$user_defined$benchmarking.original
sa_x13_ud$user_defined$benchmarking.target
sa_x13_ud$user_defined$benchmarking.result
```
### Extracting data from WS 

using rjd3 prodcuction


```{r}

library("rjd3toolkit")
library("rjd3x13")
library("rjd3workspace")

# \donttest{
# Two demo workspaces (RSA3 and RSA5)
jws_rsa3 <- create_ws_from_data(ABS, x13_spec("rsa3"))
jws_rsa5 <- create_ws_from_data(ABS, x13_spec("rsa5"))

path_rsa3 <- tempfile(pattern = "ws-rsa3", fileext = ".xml")
path_rsa5 <- tempfile(pattern = "ws-rsa5", fileext = ".xml")

save_workspace(jws_rsa3, file = path_rsa3)
save_workspace(jws_rsa5, file = path_rsa5)

df <- compare(path_rsa3, path_rsa5, series_names = "X0.2.09.10.M")
head(df)
# }

```



```{r}

library(dygraphs)
dygraph(sa_x13_ud$user_defined$full_res)

```


